spring.application.name=salary-management-backend

# SQLite datasource
spring.datasource.url=jdbc:sqlite:./data/salary-management.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=none
